name: mma
channels:
  - conda-forge
  - defaults
dependencies:
  - dash
  - dash-bootstrap-components
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - plotly
  - python=3.11.3
  - scikit-learn
  - seaborn
  - wandb